name:
  ndaab_api@v1_workflow(dev)

on:
  push:
    branches:
      - online@v1

jobs:
  create-ecs-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ECS Repository
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
          aws ecr create-repository --repository-name ${{ secrets.IMAGE_NAME }} || true